matrix:
  include:
    # Travis apparently doesn't support Python on OSX, fix that: https://github.com/travis-ci/travis-ci/issues/2312
    - language: generic
      os: osx
      before_install:
        - python3 -m venv env
        - source env/bin/activate
    - language: python
      os: linux
      python: 3.7

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost-all-dev; fi
  - pip install pytest
  - pip install .

script:
  - pytest


