#define DFACTOR_NOT_IMPL std::cout << "DFACTOR METHOD NOT IMPLEMENTED ON LINE " << __LINE__ << std::endl; DAI_THROW(NOT_IMPLEMENTED)
#define DFACTOR_CANNOT_IMPL std::cout << "DFACTOR METHOD CANNOT BE IMPLEMENTED ON LINE " << __LINE__ << std::endl; DAI_THROW(NOT_IMPLEMENTED)
