matrix:
  include:
    # Travis doesn't currently support Python on OSX, fix that: https://github.com/travis-ci/travis-ci/issues/2312
    - language: generic
      os: osx
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
    - language: python
      os: linux
      python: 3.6

branches:
  only:
    - tbp

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost-all-dev; fi
  - pip install pipenv
  - pipenv install

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then g++ --version; cp Makefile.MACOSX64 Makefile.conf; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then g++ --version; cp Makefile.LINUX Makefile.conf; fi
  - make

