mex -I../include -Ic:/boost_1_50_0 -Ic:/boost_1_50_0/boost/tr1 ...
    -Ic:/mpir-2.5.1/lib/Win32/Release ...
    -I"C:/Program Files/MATLAB/R2011b/extern/include" ...
    -Lc:/boost_1_50_0/stage/lib -LWin32\Release ...
    -Lc:/mpir-2.5.1/lib/Win32/Release ...
    -llibdai -lmpirxx -lmpir -outdir ../matlab ...
    -O -largeArrayDims -c ../src/matlab/matlab.cpp

mex -I../include -Ic:/boost_1_50_0 -Ic:/boost_1_50_0/boost/tr1 ...
    -Ic:/mpir-2.5.1/lib/Win32/Release ...
    -I"C:/Program Files/MATLAB/R2011b/extern/include" ...
    -Lc:/boost_1_50_0/stage/lib -LWin32\Release ...
    -Lc:/mpir-2.5.1/lib/Win32/Release ...
    -llibdai -lmpirxx -lmpir -outdir ../matlab ...
    -O -largeArrayDims -DWINDOWS ../src/matlab/dai.cpp ../matlab\matlab.obj

mex -I../include -Ic:/boost_1_50_0 -Ic:/boost_1_50_0/boost/tr1 ...
    -Ic:/mpir-2.5.1/lib/Win32/Release ...
    -I"C:/Program Files/MATLAB/R2011b/extern/include" ...
    -Lc:/boost_1_50_0/stage/lib -LWin32\Release ...
    -Lc:/mpir-2.5.1/lib/Win32/Release ...
    -llibdai -lmpirxx -lmpir -outdir ../matlab ...
    -O -largeArrayDims -DWINDOWS ../src/matlab/dai_potstrength.cpp ../matlab\matlab.obj

mex -I../include -Ic:/boost_1_50_0 -Ic:/boost_1_50_0/boost/tr1 ...
    -Ic:/mpir-2.5.1/lib/Win32/Release ...
    -I"C:/Program Files/MATLAB/R2011b/extern/include" ...
    -Lc:/boost_1_50_0/stage/lib -LWin32\Release ...
    -Lc:/mpir-2.5.1/lib/Win32/Release ...
    -llibdai -lmpirxx -lmpir -outdir ../matlab ...
    -O -largeArrayDims ../src/matlab/dai_readfg.cpp ../matlab\matlab.obj

mex -I../include -Ic:/boost_1_50_0 -Ic:/boost_1_50_0/boost/tr1 ...
    -Ic:/mpir-2.5.1/lib/Win32/Release ...
    -I"C:/Program Files/MATLAB/R2011b/extern/include" ...
    -Lc:/boost_1_50_0/stage/lib -LWin32\Release ...
    -Lc:/mpir-2.5.1/lib/Win32/Release ...
    -llibdai -lmpirxx -lmpir -outdir ../matlab ...
    -O -largeArrayDims ../src/matlab/dai_writefg.cpp ../matlab\matlab.obj
