mex -I../include -Ic:/boost_1_50_0 -Ic:/boost_1_50_0/boost/tr1 ...
    -Ic:/mpir-2.5.1/lib/x64/debug ...
    -I"C:/Program Files/MATLAB/R2011b/extern/include" ...
    -Lc:/boost_1_50_0/stage/lib -Lx64\debug ...
    -Lc:/mpir-2.5.1/lib/x64/debug ...
    -llibdai -lmpirxx -lmpir -outdir ../matlab ...
    -g -largeArrayDims -D_DEBUG -c ../src/matlab/matlab.cpp

mex -I../include -Ic:/boost_1_50_0 -Ic:/boost_1_50_0/boost/tr1 ...
    -Ic:/mpir-2.5.1/lib/x64/debug ...
    -I"C:/Program Files/MATLAB/R2011b/extern/include" ...
    -Lc:/boost_1_50_0/stage/lib -Lx64\debug ...
    -Lc:/mpir-2.5.1/lib/x64/debug ...
    -llibdai -lmpirxx -lmpir -outdir ../matlab ...
    -g -largeArrayDims -D_DEBUG -DWINDOWS ../src/matlab/dai.cpp ../matlab\matlab.obj

mex -I../include -Ic:/boost_1_50_0 -Ic:/boost_1_50_0/boost/tr1 ...
    -Ic:/mpir-2.5.1/lib/x64/debug ...
    -I"C:/Program Files/MATLAB/R2011b/extern/include" ...
    -Lc:/boost_1_50_0/stage/lib -Lx64\debug ...
    -Lc:/mpir-2.5.1/lib/x64/debug ...
    -llibdai -lmpirxx -lmpir -outdir ../matlab ...
    -g -largeArrayDims -D_DEBUG -DWINDOWS ../src/matlab/dai_potstrength.cpp ../matlab\matlab.obj

mex -I../include -Ic:/boost_1_50_0 -Ic:/boost_1_50_0/boost/tr1 ...
    -Ic:/mpir-2.5.1/lib/x64/debug ...
    -I"C:/Program Files/MATLAB/R2011b/extern/include" ...
    -Lc:/boost_1_50_0/stage/lib -Lx64\debug ...
    -Lc:/mpir-2.5.1/lib/x64/debug ...
    -llibdai -lmpirxx -lmpir -outdir ../matlab ...
    -g -largeArrayDims -D_DEBUG ../src/matlab/dai_readfg.cpp ../matlab\matlab.obj

mex -I../include -Ic:/boost_1_50_0 -Ic:/boost_1_50_0/boost/tr1 ...
    -Ic:/mpir-2.5.1/lib/x64/debug ...
    -I"C:/Program Files/MATLAB/R2011b/extern/include" ...
    -Lc:/boost_1_50_0/stage/lib -Lx64\debug ...
    -Lc:/mpir-2.5.1/lib/x64/debug ...
    -llibdai -lmpirxx -lmpir -outdir ../matlab ...
    -g -largeArrayDims -D_DEBUG ../src/matlab/dai_writefg.cpp ../matlab\matlab.obj
